data_name = "imagenette"
model_name = "resnet18"
algorithm = "fedhypro"
n_client = 10
n_round = 50
n_epoch = 3
device = "cuda"
lr = 0.01
he_rate = 0.1
repeat = 5
split = "iid"
save_path = "./res"

[dp]
eps = 5
delta = 1e-5
decay = 0.9
clip_thr = 1

[dynamic]
enabled = false